Add Login Screen
asherifhegazy/ShoppingXamarin pull request #1
Opened 2019-07-28 17:28 UTC by asherifhegazy

2019-07-28 17:28 UTC, asherifhegazy commented
I'm using static data for now

2019-07-29 10:33 UTC, dosama1integrant requested changes

2019-07-29 10:33 UTC, dosama1integrant commented on eShopApp/eShopApp/Global.cs
> +            else
We can remove redundant 'else' in all cases the method will return value

2019-07-29 10:33 UTC, dosama1integrant commented on eShopApp/eShopApp/Services/UserService.cs
> +            return Users;
Waiting integration with the API...

2019-07-29 16:44 UTC, dosama1integrant approved these changes

2019-07-29 20:56 UTC, merged